---
title: "MCMC Algorithm Derivation"
output: html_notebook
---

Given $XZ, k$, the log likelike hood and the composite likelihood are

$$
\begin{aligned}
\ell\left(\tau_k^{XZ^2},\mu_k^x\right) &=-\frac{1}{2} \sum_{i \in N_{XZ}^k}\left[\log \left(s_{k, i}^{XZ^2}+\tau_k^{XZ^2}\right)+\frac{\left(y_{k, i}^{XZ}-\mu_k^{XZ}\right)^2}{s_{k, i}^{XZ^2}+\tau_k^{XZ^2}}\right] \\
& =\sum_{i \in N_{XZ}^k}\left[\log \frac{1}{\sqrt{s_{k,i}^{XZ^2}+\tau_k^{XZ^2}}}-\frac{\left(y_{k, i}^{XZ}-\mu_k^{XZ}\right)^2}{2\left(s_{k, i}^{XZ^2}+\tau_k^{XZ^2}\right)}\right] \\
L\left(\tau_k^{XZ^2}, \mu_k^{XZ}\right)&=\left[\prod_{i \in N_{XZ}^k}\left(\frac{1}{\sqrt{s_{k, i}^{XZ^2}+\tau_k^{XZ^2_{}}}}\right)\right] \cdot \exp \left(\sum_{i \in N_{x_2}^k}-\frac{\left(y_{k, i}^{XZ}-\mu_k^{XZ}\right)^2}{2\left(s_{k,i}^{xz^2}+\tau_k^{XZ^2}\right)}\right) \\
&=\left[\prod_{i \in N_{XZ}^k}\left(\frac{1}{\sqrt{s_{k, i}^{XZ^2}+\tau_k^{XZ^2}}}\right)\right] \cdot \exp \left(\sum_{i \in N_{XZ}^k}-\frac{\left(y_{k, i}^{XZ}-\bar{y}_k^{XZ}\right)^2}{2\left(s_{k,i}^{XZ^2}+\tau_k^{XZ^2}\right)}-\sum_{i \in N_{k z}^k} \frac{\left(\bar{y}_k^{XZ}-\mu_k^{XZ}\right)^2}{2\left(s_{k, i}^{XZ^2}+\tau_k^{XZ^2}\right)}\right) \\
&=\left[\prod_{i \in N_{XZ}^k}\left(\frac{1}{\sqrt{s_{k,i}^{XZ^2}+\tau_k^{XZ^2}}}\right)\right] \cdot \exp \left(-\sum_{i \in N_{XZ}} \frac{\left(y_{k, i}^{XZ}-\bar{y}_k^{XZ}\right)^2}{2\left(s_{k,i}^{XZ^2}+\tau_k^{XZ}\right)}\right)\exp\left(-\sum_{i \in N_{XZ}^k} \frac{\left(\bar{y}_k^{XZ}-\mu_k^{XZ}\right)^2}{2\left(s_{k, i}^{XZ^2}+\tau_k^{XZ^2}\right)}\right) \\
&=\left[\prod_{i \in N_{XZ}^k} \frac{1}{\sqrt{s_{k,i}^{XZ^2}+\tau_k^{XZ^2}}}\right] \cdot \exp \left[\sum_{i \in N_{k z}^k}-\frac{\left(y_{k, i}^{XZ}-\bar{y}_k^{XZ}\right)^2}{2\left(s_{k,i}^{XZ}+\tau_k^{XZ^2}\right)}\right]\cdot\exp\left[\left(\bar{y}_k^{XZ}-\mu_k^{XZ}\right)^2\sum_{i \in N_{XZ}}\frac{1}{2\left(s_{k, i}^{XZ^2}+\tau_k^{XZ^2}\right)}\right]
\end{aligned}
$$
where 
$$
\begin{aligned}
n_{xz}^k &=  \sum_{i \in N_{XZ}^k}\mathbb{1}_{i \in N_{XZ}^k} \\
\bar{y}_{xz}^k &= \frac{1}{n_{xz}^k} \sum_{i \in N_{XZ}^k} y_{k,i}^{xz} 
\end{aligned}
$$

Let 
$$
\sum_{i \in N_{XZ}^k} \frac{1}{\left(s_{k,i}^{XZ}+\tau_k^{XZ^2}\right)}=\frac{n_{xz}^k}{ \sigma_k^{XZ^2}}
$$

Then the composite likelihood and marginal likelihood can also

$$
\begin{aligned}
L\left(\tau_k^{XZ^2}, \mu^{XZ}\right) &=\left[\prod_{i \in N_{XZ}^k} \frac{1}{\sqrt{s_{k, i}^{XZ^2}+\tau_k^{XZ^2}}}\right] \exp \left[\sum_{i \in N_{N k}^k}-\frac{\left(y_{k, i}^{XZ}-\bar{y}_k^{XZ}\right)^2}{2\left(s_{k,i}^{xz^2}+\tau_k^{XZ^2}\right)}\right]\exp\left[-\frac{n_{xz}^k }{2\sigma_k^{xz^2}}\left(\bar{y}_{xz}^k - \mu_k^{xz} \right)^2\right] \\
L\left(\tau_k^{XZ^2}\right) &=\int_{-\infty}^{\infty} L\left(\tau_k^{XZ^z}, \mu_k^{XZ}\right) d \mu_k^{XZ} \\
&=\left[\prod_{i \in N_{XZ}^k} \frac{1}{\sqrt{s_{k, i}^{XZ^2}+\tau_k^{XZ^2}}}\right] \exp \left[\sum_{i \in N_{N k}^k}-\frac{\left(y_{k, i}^{XZ}-\bar{y}_k^{XZ}\right)^2}{2\left(s_{k,i}^{xz^2}+\tau_k^{XZ^2}\right)}\right]\sqrt{\frac{2 \pi \sigma_k^{xz^2}}{n_{xz}^k }}\int_{-\infty}^{\infty} \sqrt{\frac{n_{xz}^k }{2 \pi \sigma_k^{xz^2}}}\exp\left[-\frac{n_{xz}^k }{2\sigma_k^{xz^2}}\left(\mu_k^{xz} - \bar{y}_{xz}^k \right)^2\right]d \mu_k^{XZ} \\
&=\left[\prod_{i \in N_{XZ}^k} \frac{1}{\sqrt{s_{k, i}^{XZ^2}+\tau_k^{XZ^2}}}\right] \exp \left[\sum_{i \in N_{N k}^k}-\frac{\left(y_{k, i}^{XZ}-\bar{y}_k^{XZ}\right)^2}{2\left(s_{k,i}^{xz^2}+\tau_k^{XZ^2}\right)}\right]\sqrt{\frac{2 \pi \sigma_k^{xz^2}}{n_{xz}^k }}
\end{aligned}
$$
Thus,by choosing $P\left(\tau_k^{XZ^2}, \mu^{XZ}\right) \propto \left(\tau_k^{XZ^2}\right)^{-1}$,  the posterior distribution of $\tau_k^{XZ^2}$ is proportional to
$$
p(\tau_k^{XZ^2}|y) \propto \left(\tau_k^{XZ^2}\right)^{-1} \left[\prod_{i \in N_{XZ}^k} \frac{1}{\sqrt{s_{k, i}^{XZ^2}+\tau_k^{XZ^2}}}\right] \exp \left[\sum_{i \in N_{N k}^k}-\frac{\left(y_{k, i}^{XZ}-\bar{y}_k^{XZ}\right)^2}{2\left(s_{k,i}^{xz^2}+\tau_k^{XZ^2}\right)}\right]\sqrt{\frac{2 \pi \sigma_k^{xz^2}}{n_{xz}^k }}
$$

$$
\begin{aligned}
p(\mu_k^{XZ} |\tau_k^{XZ^2} , y) &=\frac{P\left(\mu_k^{XZ}, \tau_k^{XZ^2}, y\right)}{P\left(\tau_k^{XZ^2}, y\right)} \\
& =\frac{p\left(y \mid \tau_k^{XZ^2}, \mu_k^{XZ}\right) \cdot P\left(\tau_k^{XZ^2},\mu_k^{XZ}\right)}{p\left(\tau_k^{XZ^2}, y\right)} \\
& =\frac{P\left(y \mid \tau_k^{XZ^2}, \mu_k^{XZ}\right) P\left(\tau_k^{XZ^2}, \mu_k^{XZ}\right)}{P\left(y \mid \tau_k^{XZ^2}\right) P\left(\tau_k^{XZ^2}\right)} \\
&\propto \frac{L\left(\tau_k^{XZ^2}, \mu_k^{XZ}\right)}{L\left(\tau_k^{XZ^2}\right)} \\
&= \sqrt{\frac{n_{XZ}^k }{2 \pi \sigma_k^{xz^2}}}\exp\left[-\frac{n_{xz}^k}{2\sigma_k^{xz^2}}\left(\bar{y}_{XZ}^k - \mu_k^{XZ} \right)^2\right] 
\end{aligned}
$$

where 

$$
\begin{aligned}
P\left(\tau_k^{XZ^2},\mu_k^{XZ}\right) &\propto\left(\tau_k^{XZ^2}\right)^{-1} \\
\frac{P\left(\tau_k^{XZ^2},\mu_k^{XZ}\right)}{P\left(\tau_k^{XZ^2}\right)} &\propto 1
\end{aligned}
$$


Algorithm: Gibbs Sampling algorithm

Input: $\hat{\eta}_c$, $H\left(\eta\right)_c$, $J\left(\hat{\eta}_c\right)$, a proposal distribution $q$ and adjusted composite likelihood $L_{adj}$

Output: A realization of length $N+1$ from a Markov Chain

| for $k \in \{1,2\}$
|     for $t$ from 1 to N
|         for $XZ \in \{AB, AC, BC\}$
|               sample $\tau_k^{XZ(p)} \sim  p(\tau_k^{XZ^2}|y)$
|               sample $\mu_k^{XZ(p)} \sim N(\bar{y}_{XZ}^k, \frac{\left(\sigma_k^{XZ}\right)^2}{n_{xz}^k})$ where $\frac{\left(\sigma_k^{XZ}\right)^2}{n_{xz}^k} = \frac{1 }{\sum_{i \in N_{XZ}^k} \frac{1}{\left(s_{k,i}^{XZ}+\tau_k^{XZ^2}\right)}}$ and $\bar{y}_{xz}^k = \frac{1}{n_{xz}^k} \sum_{i \in N_{XZ}^k} y_{k,i}^{xz}$
|       $\tau_k^p = \left\{\tau_k^{BA}, \tau_k^{AC}, \tau_k^{BC}\right\}$
|       $\mu_k^p = \left\{\mu_k^{BA}, \mu_k^{AC}, \mu_k^{BC}\right\}$
|       $a = \frac{\prod_{XZ \in \{AB, AC, BC\}}P\left(\mu_k^{XZ(p)}|y,\tau_k^{XZ^2(p)}\right)P\left(\tau_k^{XZ^2(p)}|y\right)}{\prod_{XZ \in \{AB, AC, BC\}} P\left(\mu_k^{XZ(t-1)}|y,\tau_k^{XZ^2(t-1)}\right)P\left(\tau_k^{XZ^2(t-1)}|y\right)}$
|       if $runif(1) <= min\left(1,a\right):$
|           $\tau_k^t = \tau_k^p$
|           $\mu_k^t = \mu_k^p$
|       else:
|           $\tau_k^t = \tau_k^{t-1}$
|           $\mu_k^t = \mu_k^{t-1}$

















