---
title: "Frequentist Network Meta-Analysis in R"
author: "Yifei Wang"
date: '2023-05-12'
output: html_document
---

```{r setup, include=FALSE}
library(netmeta)
library(MASS)
```

## Data Preparation

```{r cars}
source("CLNMA_functions.R")
set.seed(1)
mu1 = c(0.5,1)
mu2 = c(0,-0.5)
tau1 =c(0.25,0.36)
tau2 =c(0.36,0.16)

tau = c(tau1,tau2)
rho = matrix(c(1,0.1,0.1,0.1,0.1,1,0.1,0.1,0.1,0.1,1,0.1,0.1,0.1,0.1,1),
             nrow = 4)
tau_BC = tau1+tau2-2*rho[1,2]*sqrt(tau1*tau2)


betweenv = diag(tau)
for(i in 1:3){
  for(j in (i+1):4){
    betweenv[i,j] =betweenv[j,i]= rho[i,j]*sqrt(tau[i]*tau[j])
  }
}
ss1 =1
ss2= 1
rho_w = matrix(c(1,0.2,0.2,0.2,0.2,1,0.2,0.2,0.2,0.2,1,0.2,0.2,0.2,0.2,1),
               nrow = 4)
nab = nac=nbc=nabc=5
dataout = gendata(nab,nac,nbc,nabc,mu1,mu2,betweenv,rho_w,ss1,ss2)
dataout1 = subset(dataout, select = c("ID", "outcome1", "sd1", "t1", "t2"))
colnames(dataout1) = c("author", "TE", "seTE", "treat1", "treat2")
dataout2 = subset(dataout, select = c("ID", "outcome2", "sd2", "t1", "t2"))
colnames(dataout2) = c("author", "TE", "seTE", "treat1", "treat2")
```

```{r}
head(dataout1)
```

```{r}
head(dataout2)
```

## Model fitting

```{r}
m.netmeta1<- netmeta(TE = TE,
                     seTE = seTE,
                     treat1 = treat1,
                     treat2 = treat2,
                     studlab = author,
                     data = dataout1,
                     sm = "SMD",
                     fixed = TRUE,
                     random = FALSE,
                     reference.group = 3,
                     details.chkmultiarm = TRUE,
                     sep.trts = " vs ")
summary(m.netmeta1)
```

```{r}
forest(m.netmeta1, 
       reference.group = 3)
```


```{r}
m.netmeta2<- netmeta(TE = TE,
                     seTE = seTE,
                     treat1 = treat1,
                     treat2 = treat2,
                     studlab = author,
                     data = dataout2,
                     sm = "SMD",
                     fixed = TRUE,
                     random = FALSE,
                     reference.group = 3,
                     details.chkmultiarm = TRUE,
                     sep.trts = " vs ")
summary(m.netmeta2)
```

```{r}
forest(m.netmeta2, 
       reference.group = 3)
```

