---
title: "Result"
output: html_notebook
---

```{r}
mu1 = c(0.5,1)
mu2 = c(0,-0.5)
mu1[3] = mu1[1] - mu1[2]
mu2[3] = mu2[1] - mu2[2]
```

Result from Gemtc

```{r}
load('gemtc_simulation_2023-05-15.RData')
gemtc_estimate1 = colMeans(estimated_mu1)
names(gemtc_estimate1) = c("BA", "CA", "BC")
gemtc_estimate1[3]  = gemtc_estimate1[1] - gemtc_estimate1[2]
print("Estimated value")
print(gemtc_estimate1)
print("Bias")
print(round(abs(gemtc_estimate1 - mu1),4))
```

```{r}
gemtc_estimate2 = colMeans(estimated_mu2)
names(gemtc_estimate2) = c("BA", "CA", "BC")
gemtc_estimate2[3]  = gemtc_estimate2[1] - gemtc_estimate2[2]
print("Estimated value")
print(gemtc_estimate2)
print("Bias")
print(round(abs(gemtc_estimate2 - mu2),4))
```
Results from netmeta

```{r}
load('netmeta_simulation_2023-05-15.RData')
netmeta_estimate1 = colMeans(estimated_mu1)
netmeta_estimate1[3]  = netmeta_estimate1[1] - netmeta_estimate1[2]
names(netmeta_estimate1) = c("BA", "CA", "BC")
print("Estimated value")
print(netmeta_estimate1)
print("Bias")
print(round(abs(netmeta_estimate1 - mu1),4))
```

```{r}
netmeta_estimate2 = colMeans(estimated_mu2)
netmeta_estimate2[3]  = netmeta_estimate2[1] - netmeta_estimate2[2]
names(netmeta_estimate2) = c("BA", "CA", "BC")
print("Estimated value")
print(netmeta_estimate2)
print("Bias")
print(round(abs(netmeta_estimate2 - mu2),4))
```

results from the composite likelihood

```{r}
load('simulation_result_2023-05-18.RData')
simulation_result_matrix =  matrix(simulation_result, ncol = 12, byrow = T)
estimated_mu1 = colMeans(simulation_result_matrix[,1:2])
estimated_mu1[3] = estimated_mu1[1] - estimated_mu1[2] 
names(estimated_mu1) = c("BA", "CA", "BC")
print("Estimated value")
print(estimated_mu1)
print("Bias")
print(round(abs(estimated_mu1 - mu1),4))
```
```{r}
estimated_mu2 = colMeans(simulation_result_matrix[,4:5])
estimated_mu2[3] = estimated_mu2[1] - estimated_mu2[2]  
names(estimated_mu2) = c("BA", "CA", "BC")
print("Estimated value")
print(estimated_mu2)
print("Bias")
print(round(abs(estimated_mu2 - mu2),4))
```

Summary

Outcome1 Bisa

```{r, warning=FALSE}
method <- c("Gemtc", "Netmeta", "Composite Likelihood")
outcome1_result <- data.frame(
  Method = method,
  BA = c(abs(gemtc_estimate1 - mu1)[1],abs(netmeta_estimate1 - mu1)[1], abs(estimated_mu1 - mu1)[1]),
  CA = c(abs(gemtc_estimate1 - mu1)[2],abs(netmeta_estimate1 - mu1)[2], abs(estimated_mu1 - mu1)[2]),
  BC = c(abs(gemtc_estimate1 - mu1)[3],abs(netmeta_estimate1 - mu1)[3], abs(estimated_mu1 - mu1)[3])
)
outcome1_result[,-1] = round(outcome1_result[,-1],4)
print(outcome1_result)
```

Outcome2 Bias

```{r}
outcome2_result <- data.frame(
  Method = method,
  BA = c(abs(gemtc_estimate2 - mu2)[1],abs(netmeta_estimate2 - mu2)[1], abs(estimated_mu2 - mu2)[1]),
  CA = c(abs(gemtc_estimate2 - mu2)[2],abs(netmeta_estimate2 - mu2)[2], abs(estimated_mu2 - mu2)[2]),
  BC = c(abs(gemtc_estimate2 - mu2)[3],abs(netmeta_estimate2 - mu2)[3], abs(estimated_mu2 - mu2)[3])
)
outcome2_result[,-1] = round(outcome2_result[,-1],4)
print(outcome2_result)
```

```{r}
dim(simulation_result_matrix[,1:2])
```

```{r}
hist(simulation_result_matrix[,1])
```

```{r}
hist(simulation_result_matrix[,2])
```

